Two configurable variables were ignored
brunoarine/org-similarity pull request #34
Opened 2024-02-05 02:35 UTC by bramadams

Variables `org-similarity-prefix' and `org-similarity-heading'
were shadowed by local variables. Removed those declarations.

2024-02-11 15:39 UTC, brunoarine commented
Hello @bramadams, and thank you for the PR. These variables are intentionally overridden when showing results in the side buffer. I didn't want the customization in my org notes "related" section to be reflected in the side buffer, which is really just a temporary buffer for quick checks.

But since you saw need to customize it, I believe others may have the same need. Therefore I'm creating two more variables specifically for the side buffer.

2024-02-11 15:49 UTC, brunoarine requested changes
Please replace these lines with the following code:

```lisp
(let* ((org-similarity-heading org-similarity-heading-sidebuffer)
         (org-similarity-prefix org-similarity-prefix-sidebuffer)
```
And then define these two new variables in the beginning of the file with the hard-coded values "Similarity results\n" and "" respectively, so we avoid breaking others' workflow.

2024-02-11 16:38 UTC, bramadams commented
> Please replace these lines with the following code:
> 
> ```lisp
> (let* ((org-similarity-heading org-similarity-heading-sidebuffer)
>          (org-similarity-prefix org-similarity-prefix-sidebuffer)
> ```
> 
> And then define these two new variables in the beginning of the file with the hard-coded values "Similarity results\n" and "" respectively, so we avoid breaking others' workflow.

Thanks for the suggestion, I incorporated it in this new commit.

2024-02-14 14:07 UTC, merged

2024-02-15 02:27 UTC, bramadams commented
Great, thanks!